### ISSUE TITLE
Move JWT config from global.php to a local file

### ISSUE THREAD

**Issue by DLMousey** [DLMousey/ZF3-Jwt-Api#2]
JWT config with the signing key is currently in the `config/global.php` file - This is fine for example purposes but in the real world this needs to be in an untracked `config/*.local.php` file so it can be added to the gitignore.

As well as relocating the file, a `*.local.php.dist` variant needs to be created with dummy values so developers can see how they should use the file.

A simple composer script for copying the example to a live version would also be nice but not _required_.

**Comment by raphaelts3** [comment]
Hello @DLMousey I have a lot of interest in ZF3, can I help you with that?

**Comment by DLMousey** [comment]
Course you can @raphaelts3, Thanks for offering.
In the `config` directory there's a `jwt.local.php` file which i think would be a good place to put the config items from `global.php`, It'd just be a case of moving them into there and adjusting a few factories to get the right items from the config
