### ISSUE TITLE
Create documentation

### ISSUE THREAD

**Issue by DLMousey** [DLMousey/ZF3-Jwt-Api#5]
This project is in need of some documentation - At first i was thinking of putting it within the app itself since, hey, it's a ZF3 app and we've got the full MVC module but then realised if anyone bases their own ZF3 project off this it's just another thing to remove.

Instead we'll make use of Github pages. 
Let's make some documentation that's both pretty and helpful - I was thinking something in the style of the [Laravel docs](https://laravel.com/docs/5.7) since they're widely regarded as the gold standard in framework documentation

If anybody has their own ideas for a design please do share them

**Comment by DLMousey** [comment]
Should have probably clarified in the original issue that a Github Wiki will also be acceptable as a stop gap until we've got something custom in place.

**Comment by davidquintard** [comment]
Hi there,
How to use ?
No login page to test jwt ?

**Comment by DLMousey** [comment]
Hi, this repo's meant to be used in conjunction with the [angular client](https://github.com/DLMousey/ZF3-Jwt-Api-Client).

This repo was built to demonstrate using JWTs with a separate javascript app on the front end

**Comment by davidquintard** [comment]
This is a very great job!
But where cors is configured ?

OPTIONS seems not declared into allowed headers:

````
Request URL: http://localhost/ZF3-Jwt-Api/public/unprotected
Request Method: OPTIONS
Status Code: 405 Method Not Allowed
Remote Address: [::1]:80
Referrer Policy: no-referrer-when-downgrade

RESPONSE HEADERS:
Connection: Keep-Alive
Content-Length: 0
Content-Type: text/html; charset=UTF-8
Date: Sat, 09 Nov 2019 17:19:35 GMT
Keep-Alive: timeout=5, max=100
Server: Apache/2.4.41 (Win64) OpenSSL/1.1.1c PHP/7.3.11
X-Powered-By: PHP/7.3.11

REQUEST HEADERS:
Accept: */*
Accept-Encoding: gzip, deflate, br
Accept-Language: fr-FR,fr;q=0.9,en-US;q=0.8,en;q=0.7,vi;q=0.6
Access-Control-Request-Headers: authorization
Access-Control-Request-Method: GET
Connection: keep-alive
Host: localhost
Origin: http://localhost:4200
Referer: http://localhost:4200/
Sec-Fetch-Mode: cors
Sec-Fetch-Site: same-site
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.97 Safari/537.36
````

**Comment by DLMousey** [comment]
This does seem to be an oversight on my part, i'll get that fixed up. Nice catch thanks very much

**Comment by davidquintard** [comment]
I added options() method into controllers to manage OPTIONS requests.
It works fine now !

**Comment by DLMousey** [comment]
You'd typically apply the CORS headers at the NGINX/Apache level rather than at the apache level, having said that this repo does need a mechanism for handling these in development
